# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aa0cabc085d6d80bf6f16a8db268e6c71c52fe32333d3ad69fe966a4566050f195cec61e02f886c19194d38db73d84c566c806db6517beee5908acca62f83ab

test:
  secret_key_base: 2828f0f7195f190a2bafd7ed9e3e119766d9a3ad907ba4e0531058c2b8ccbd5f119263f04982cdac49a9573c1b1cfdd14436a469a4dbe77a25ff54572cac30b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
